#!/usr/bin/env -S npx tsx
/**
 * OpenUISpec CLI
 *
 * Usage:
 *   openuispec init                           Create a new spec project
 *   openuispec init --defaults                Scaffold non-interactively with defaults
 *   openuispec configure-target <t>           Configure target stack and managed dependencies
 *   openuispec drift [--target <t>]           Check for spec drift
 *   openuispec drift --snapshot --target <t>  Snapshot current state + git baseline
 *   openuispec drift --target <t> --explain   Explain semantic changes since baseline
 *   openuispec prepare --target <t>           Build the target work bundle
 *   openuispec status                         Show cross-target baseline/drift status
 *   openuispec validate [group...]            Validate spec files against schemas
 */

import { init, updateRules, extractRulesVersion, getPackageVersion } from "./init.js";
import { join } from "node:path";
import { existsSync, readFileSync } from "node:fs";

function checkRulesVersion(): void {
  const cwd = process.cwd();
  const installed = getPackageVersion();
  for (const file of ["CLAUDE.md", "AGENTS.md"]) {
    const filePath = join(cwd, file);
    if (!existsSync(filePath)) continue;
    const rulesVersion = extractRulesVersion(filePath);
    if (rulesVersion && rulesVersion !== installed) {
      console.log(
        `\n⚠  ${file} rules were generated by v${rulesVersion} but v${installed} is installed.` +
        `\n   Run: openuispec update-rules\n`
      );
    } else if (!rulesVersion) {
      const content = readFileSync(filePath, "utf-8");
      if (content.includes("OpenUISpec")) {
        console.log(
          `\n⚠  ${file} has OpenUISpec rules without a version marker.` +
          `\n   Run: openuispec update-rules\n`
        );
      }
    }
  }
}

async function main(): Promise<void> {
  const [command, ...rest] = process.argv.slice(2);

  switch (command) {
    case "init":
      await init(rest);
      break;

    case "update-rules":
      updateRules();
      break;

    case "configure-target": {
      const { runConfigureTarget } = await import("./configure-target.js");
      await runConfigureTarget(rest);
      break;
    }

    case "drift": {
      const { runDrift } = await import("../drift/index.js");
      runDrift(rest);
      break;
    }

    case "prepare": {
      const { runPrepare } = await import("../prepare/index.js");
      runPrepare(rest);
      break;
    }

    case "status": {
      const { runStatus } = await import("../status/index.js");
      runStatus(rest);
      break;
    }

    case "validate": {
      const { runValidate } = await import("../schema/validate.js");
      runValidate(rest);
      checkRulesVersion();
      break;
    }

    case undefined:
    case "--help":
    case "-h":
      console.log(`
OpenUISpec CLI v0.1

Usage:
  openuispec init                           Create a new spec project
  openuispec init --defaults                Scaffold non-interactively with defaults
  openuispec init --no-configure-targets    Skip target stack setup during init
  openuispec update-rules                   Update AI rules to match installed version
  openuispec configure-target <t> [--defaults] Configure target stack and managed dependencies
  openuispec drift [--target <t>]           Check for spec drift
  openuispec drift --snapshot --target <t>  Snapshot current state + git baseline
  openuispec drift --target <t> --explain   Explain semantic changes since baseline
  openuispec prepare --target <t>           Build the target work bundle
  openuispec status                         Show cross-target baseline/drift status
  openuispec validate [group...]            Validate spec files

Validate groups: manifest, tokens, screens, flows, platform, locales, contracts, semantic

Docs: https://openuispec.rsteam.uz
`);
      break;

    default:
      console.error(`Unknown command: ${command}`);
      console.error(`Run "openuispec --help" for usage.`);
      process.exit(1);
  }
}

main();
