/**
 * Emits Localizable.strings and L10n helper from locale data.
 */

import { fileHeader, escapeSwiftString } from "./swift-utils.js";

export function emitLocalizableStrings(strings: Record<string, string>): string {
  let code = `/* Localizable.strings — Generated by OpenUISpec iOS Generator */\n\n`;

  for (const [key, value] of Object.entries(strings)) {
    code += `"${escapeSwiftString(key)}" = "${escapeSwiftString(value)}";\n`;
  }

  return code;
}

export function emitL10nHelper(strings: Record<string, string>): string {
  let code = fileHeader("L10n.swift");
  code += `import Foundation\n\n`;

  code += `enum L10n {\n`;

  for (const key of Object.keys(strings)) {
    const propName = dotToCamel(key);
    code += `    static let ${propName} = NSLocalizedString("${escapeSwiftString(key)}", comment: "")\n`;
  }

  code += `\n    /// Look up a localization key at runtime.\n`;
  code += `    static func string(_ key: String) -> String {\n`;
  code += `        NSLocalizedString(key, comment: "")\n`;
  code += `    }\n`;
  code += `}\n`;

  return code;
}

function dotToCamel(dotted: string): string {
  return dotted
    .split(".")
    .map((part, i) => {
      const camel = part.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
      return i === 0 ? camel : camel.charAt(0).toUpperCase() + camel.slice(1);
    })
    .join("");
}
