/**
 * Swift code generation utilities.
 */

/** Indent each line of a string by `level` × 4 spaces. */
export function indent(code: string, level: number): string {
  const prefix = "    ".repeat(level);
  return code
    .split("\n")
    .map((line) => (line.trim() === "" ? "" : prefix + line))
    .join("\n");
}

/** Convert "snake_case" to "camelCase". */
export function camelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

/** Convert "snake_case" to "PascalCase". */
export function pascalCase(s: string): string {
  const cc = camelCase(s);
  return cc.charAt(0).toUpperCase() + cc.slice(1);
}

/** Convert hex color "#RRGGBB" to Swift Color literal. */
export function hexToSwiftColor(hex: string): string {
  const h = hex.replace("#", "");
  const r = parseInt(h.substring(0, 2), 16) / 255;
  const g = parseInt(h.substring(2, 4), 16) / 255;
  const b = parseInt(h.substring(4, 6), 16) / 255;
  return `Color(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)})`;
}

/** Escape a string for use inside a Swift string literal. */
export function escapeSwiftString(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
}

/** Swift font weight from numeric value. */
export function swiftFontWeight(w: number): string {
  if (w >= 700) return ".bold";
  if (w >= 600) return ".semibold";
  if (w >= 500) return ".medium";
  return ".regular";
}

/** Generate a Swift file header comment. */
export function fileHeader(filename: string): string {
  return `// ${filename}
// Generated by OpenUISpec iOS Generator
// DO NOT EDIT — this file is auto-generated

import SwiftUI
`;
}

/** Wrap content in a Swift extension. */
export function swiftExtension(type: string, body: string): string {
  return `extension ${type} {\n${indent(body, 1)}\n}`;
}
